// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNvRpgZRZHSqfQoaVT53YyCk3uSPvMEmw',
    appId: '1:142771374477:web:970e26bd071fd9f76415c4',
    messagingSenderId: '142771374477',
    projectId: 'catcare-d0fb0',
    authDomain: 'catcare-d0fb0.firebaseapp.com',
    storageBucket: 'catcare-d0fb0.appspot.com',
    measurementId: 'G-M42T3X5EDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa_xjst6K-lGmTKGGyQd9ABNx_cv8X10o',
    appId: '1:142771374477:android:24223b12b7b492a76415c4',
    messagingSenderId: '142771374477',
    projectId: 'catcare-d0fb0',
    storageBucket: 'catcare-d0fb0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAwrsY9kFvsmG0ld6RDhks1sywClc2rp8',
    appId: '1:142771374477:ios:1ed56e8681ff9fb16415c4',
    messagingSenderId: '142771374477',
    projectId: 'catcare-d0fb0',
    storageBucket: 'catcare-d0fb0.appspot.com',
    iosBundleId: 'com.example.demoMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAwrsY9kFvsmG0ld6RDhks1sywClc2rp8',
    appId: '1:142771374477:ios:1ed56e8681ff9fb16415c4',
    messagingSenderId: '142771374477',
    projectId: 'catcare-d0fb0',
    storageBucket: 'catcare-d0fb0.appspot.com',
    iosBundleId: 'com.example.demoMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNvRpgZRZHSqfQoaVT53YyCk3uSPvMEmw',
    appId: '1:142771374477:web:022548002f7dff756415c4',
    messagingSenderId: '142771374477',
    projectId: 'catcare-d0fb0',
    authDomain: 'catcare-d0fb0.firebaseapp.com',
    storageBucket: 'catcare-d0fb0.appspot.com',
    measurementId: 'G-03WGYQGPCM',
  );
}
